### PR TITLE
made revisions/additions to chapter 1

### PR DESCRIPTION
**Pull request by westutz**
Max, I made some edits for chapter 1. Mostly fleshing out little bits here or there, annotating some basic code, especially in the beginning. Feel free to keep, modify, or drop anything you want.

P.S. I hope did this pull request correctly. It's my first...

### CODE REVIEW

**Comment by mbjoseph** [comment]
Awesome, thanks! It looks like the diff is a little screwy, but this looks good.

**Comment by westutz** [comment]
Ahh...My text editor doesn't have native spell check so I cut and pasted 
into word and then cut and pasted back. I wonder if that's what caused 
the issue....

Postdoctoral Research Associate
University of Colorado, Boulder
Department of Ecology and Evolutionary Biology
william.stutz@colorado.edu

**Comment by mbjoseph** [comment]
You should check out Atom: https://atom.io/

**Comment by westutz** [comment]
That looks neat!

Postdoctoral Research Associate
University of Colorado, Boulder
Department of Ecology and Evolutionary Biology
william.stutz@colorado.edu

**Pull request merged**
